name: writeapaper

on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      DIR: .
      FILE: Bari_Vahidov_CV
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install TeX Live from installer
        run: |
          sudo apt-get update
          sudo apt-get install -y perl wget tar xz-utils
          wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xzf install-tl-unx.tar.gz
          cd install-tl-*
          echo "selected_scheme scheme-small" > texlive.profile
          echo "tlpdbopt_install_docfiles 0" >> texlive.profile
          echo "tlpdbopt_install_srcfiles 0" >> texlive.profile
          sudo ./install-tl -profile texlive.profile
          echo "::add-path::/usr/local/texlive/2024/bin/x86_64-linux"

      - name: Install required TeX packages
        run: |
          sudo /usr/local/texlive/2024/bin/x86_64-linux/tlmgr install \
            latexmk biblatex cm-super graphics geometry enumitem multirow xcolor parskip url titlesec supertabular

      - name: Compile LaTeX
        working-directory: ${{ env.DIR }}
        run: |
          /usr/local/texlive/2024/bin/x86_64-linux/pdflatex ${{ env.FILE }}
          /usr/local/texlive/2024/bin/x86_64-linux/bibtex ${{ env.FILE }}
          /usr/local/texlive/2024/bin/x86_64-linux/pdflatex ${{ env.FILE }}
          /usr/local/texlive/2024/bin/x86_64-linux/pdflatex ${{ env.FILE }}

      - name: Move PDF to artifacts
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf github_artifacts/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts

  deploy:
    needs: [paper]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: github_artifacts

      - name: Move artifact to deploy folder
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy

      - name: Deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true